# Generated by Django 3.1.2 on 2020-10-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='blank', max_length=64)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('school_long', models.CharField(default='blank', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wis_id', models.PositiveIntegerField(unique=True)),
                ('school_long', models.CharField(max_length=64)),
                ('school_short', models.CharField(max_length=40)),
                ('world', models.CharField(max_length=15)),
                ('division', models.CharField(blank=True, max_length=8)),
                ('conference', models.CharField(blank=True, max_length=64)),
                ('coach', models.CharField(default='Sim AI', max_length=64)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collegetown', to='gdanalyst.city')),
            ],
        ),
    ]
